### ISSUE TITLE
Change DNS for new host

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/codefordenver.org#160]
@seankwilliams I feel like this is the rudest way to ask this of you but I couldn't figure out what a nicer way!

Could we get you to update the DNS for CFD.org? We're switching off of the github pages and going to bluehost. 

Just let me know what you need to update it, looks like we got nameservers here and need the EPP code? 

![image](https://user-images.githubusercontent.com/17071865/119369071-fce29980-bc70-11eb-998c-30715ae4294f.png)

**Comment by seankwilliams** [comment]
@anotherpatrickcollins lol no worries! Hope you're doing well.

I just updated the DNS but codefordenver.org is showing a generic landing page though - http://codefordenver.org/:

![image](https://user-images.githubusercontent.com/151931/119392889-ec90e580-bc95-11eb-84cd-39f3282fc8ff.png)

There might just be a step or two you'll have to finish in BlueHost. Let me know if you want me to switch the DNS back to GitHub pages for a bit in the meantime.

Right now, I'm still managing the nameservers (rather than switch the nameservers, I changed the A record according to BlueHost's instructions). If you want to move the nameservers to BlueHost, we can do that. That would make it so you guys could manage all the DNS on your end. Only disadvantage is that there's about 20 DNS records we'd have to copy over in order to do it. I'm happy to keep managing the records -- just wanted to mention that in case it would make things easier.

**Comment by anotherpatrickcollins** [comment]
Omg my notifications were off. lol.

I'll look into this ASAP Sean, thank you so much for following up!

**Comment by anotherpatrickcollins** [comment]
It was a setting on our end (had to tell it what directory) and it looks like it's live now! Thank you again so much Sean.

We'll discuss the DNS records - might be good to have them in house just for that continuity of knowledge but we'll have to figure out if we can do it ourselves or not! ha

Thanks, I'll ping you on GH when we are done chatting about it. 

Closing this for now. 

P

**Comment by seankwilliams** [comment]
@anotherpatrickcollins awesome, glad that the site is live! Just let me know whatever you decide on DNS.

**Comment by anotherpatrickcollins** [comment]
Hey @seankwilliams I actually have a whole OTHER DNS thing that needs to be taken care of but includes a key that probably shouldn't be public - any way you could email me patrick@codefordenver.org and we can coordinate over that? 

It's DKIM signing for some CFA email security on our domain.
